#%RAML 1.0 DataType
type: object
properties:
  data:
    type: array
    items:
      properties:
        ID Nation:
          type: string
          description: Id nation
        Nation:
          type: string
          description: Nation
        ID Year:
          type: integer
          description: Id year
        Population:
          type: integer
          description: Population
        Slug Nation:
          type: string
          description: Slug nation
         